server:
  port: 8091
  tomcat:
    threads:
      max: 10
spring:
  cloud:
    sentinel:
      transport:
        port: 9999
        dashboard: localhost:8080
      web-context-unify: false
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///shop-order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
